version: "3.7"

services:
  python:
    build: .
    command: tail -f /dev/null
    container_name: dash-datepicker
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8050:8050"
      - "55555:55555"
